version: '3.9'

services:
  iterable-string-dev:
    image: iterable-string-dev
    container_name: iterable-string-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /iterable-string
    volumes:
      - ..:/iterable-string:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
